name: Publish latest XLSX to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - latest/allw-latest.xlsx
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare artifact
        run: |
          mkdir -p public/latest
          cp latest/allw-latest.xlsx public/latest/allw-latest.xlsx
          cp latest/allw-latest.sha256 public/latest/allw-latest.sha256
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
